services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - pictionary-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    environment:
      - PORT=8080
      - GO_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_go_mod_cache:/go/pkg/mod
      - backend_go_build_cache:/root/.cache/go-build
    networks:
      - pictionary-network
    restart: unless-stopped

networks:
  pictionary-network:
    driver: bridge

volumes:
  backend_go_mod_cache:
  backend_go_build_cache: 